apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 1m
  chart:
    spec:
      chart: trivy-operator
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: aquasecurity-charts
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: -1
  values:
    - trivy.ignoreUnfixed=true