apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aquasecurity-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://aquasecurity.github.io/helm-charts/